name: Automate Data Scraping

on:
  schedule:
    # Run the workflow every day at :300 UTC
    - cron: '0 3 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  scrape-data:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Run the Python script
    - name: Run scraper
      run: python rockfm_scrap.ipynb

    # Step 5: Push changes to the repository
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add songs.csv
        git commit -m "Update songs CSV file via GitHub Action"
        git push


